# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='category',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
    ]
